# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_files_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
