# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 16:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0003_auto_20170815_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileViewing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('seconds_viewed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ViewingPermissionToken',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='viewingpermissiontoken',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.Files'),
        ),
        migrations.AddField(
            model_name='viewingpermissiontoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileviewing',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.Files'),
        ),
        migrations.AddField(
            model_name='fileviewing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
