# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_auto_20170815_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='slug',
            field=models.SlugField(help_text="Automatically generated text for links, please make sure it's unique for files with same name.", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='title',
            field=models.CharField(help_text='Title of the document/video.', max_length=100),
        ),
    ]
